[build]
  base = "/"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --verbose"
  CI = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  DEBUG = "*"

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
