[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  VITE_NODE_VERSION = "18"
  # Allow SUPABASE_ANON_KEY in built files (it's a public key)
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,VITE_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_ANON_KEY,JWT_SECRET"
  # Omit dist folder from secrets scanning as it contains bundled frontend code
  SECRETS_SCAN_OMIT_PATHS = "dist/**/*,dist/assets/**/*"
  
# These variables must be set in the Netlify UI
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_ANON_KEY = "your-supabase-anon-key"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "@supabase/supabase-js", "socket.io"]
  included_files = ["netlify/functions/**/*"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/support-chat/*"
  to = "/.netlify/functions/support-chat/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/support-chat"
  to = "/.netlify/functions/support-chat"
  status = 200
  force = true

[[redirects]]
  from = "/test-simple"
  to = "/.netlify/functions/test-simple"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Content-Length, X-Requested-With"
