-- Financial Management Tables
-- Payments, Invoices, Invoice Items, Invoice Settings, Coupons
-- Date: 2025-08-24

CREATE TABLE IF NOT EXISTS payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  payment_method varchar(50) NOT NULL,
  payment_status varchar(20) NOT NULL,
  transaction_id varchar(255),
  payment_details jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  invoice_number text NOT NULL,
  customer_name text NOT NULL,
  customer_phone text,
  customer_email text,
  billing_address text,
  invoice_date timestamp with time zone DEFAULT now(),
  due_date timestamp with time zone,
  subtotal numeric NOT NULL,
  tax_amount numeric NOT NULL,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  status invoice_status DEFAULT 'draft'::invoice_status,
  payment_method text,
  notes text,
  terms_and_conditions text,
  is_printed boolean DEFAULT false,
  print_count integer DEFAULT 0,
  last_printed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  display_order_id text,
  template_id uuid,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid,
  item_name text NOT NULL,
  description text,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  tax_rate numeric DEFAULT 0.18,
  tax_amount numeric NOT NULL,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS invoice_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid,
  template_name varchar(50) NOT NULL DEFAULT 'default'::character varying,
  company_name varchar(100),
  company_address text,
  company_phone varchar(20),
  company_email varchar(100),
  company_website varchar(100),
  company_logo_url text,
  primary_color varchar(10) DEFAULT '#f97316'::character varying,
  secondary_color varchar(10) DEFAULT '#ffa500'::character varying,
  accent_color varchar(10) DEFAULT '#000000'::character varying,
  header_text text,
  footer_text text,
  terms_conditions text,
  tax_label_1 varchar(20) DEFAULT 'CGST'::character varying,
  tax_rate_1 numeric(5,2) DEFAULT 9.00,
  tax_label_2 varchar(20) DEFAULT 'SGST'::character varying,
  tax_rate_2 numeric(5,2) DEFAULT 9.00,
  include_tax_breakdown boolean DEFAULT true,
  invoice_prefix varchar(10) DEFAULT ''::character varying,
  invoice_suffix varchar(10) DEFAULT ''::character varying,
  date_format varchar(20) DEFAULT 'dd MMM yyyy'::character varying,
  receipt_width integer DEFAULT 80,
  receipt_title varchar(50) DEFAULT 'RECEIPT'::character varying,
  show_restaurant_contact boolean DEFAULT true,
  include_qr_code boolean DEFAULT false,
  qr_code_content text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  watermark_text text,
  watermark_opacity numeric(3,2) DEFAULT 0.1,
  custom_css text,
  custom_header_html text,
  custom_footer_html text,
  include_signature_field boolean DEFAULT false,
  signature_text text,
  digital_signature_url text,
  font_family varchar(100) DEFAULT 'helvetica'::character varying,
  custom_fields jsonb DEFAULT '[]'::jsonb,
  item_table_columns jsonb DEFAULT '["Item", "Qty", "Price", "Amount"]'::jsonb,
  page_size varchar(20) DEFAULT 'A4'::character varying,
  page_orientation varchar(20) DEFAULT 'portrait'::character varying,
  currency_symbol varchar(10) DEFAULT 'Rs'::character varying,
  currency_format varchar(20) DEFAULT 'symbol_before'::character varying,
  enable_auto_numbering boolean DEFAULT true,
  show_paid_stamp boolean DEFAULT true,
  show_overdue_stamp boolean DEFAULT false,
  itemized_tax_display boolean DEFAULT false,
  barcode_type varchar(20) DEFAULT 'qr'::character varying,
  barcode_content text,
  include_payment_instructions boolean DEFAULT false,
  payment_instructions text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS coupons (
  id integer NOT NULL DEFAULT nextval('coupons_id_seq'::regclass),
  code varchar(50) NOT NULL,
  discount_type varchar(20) NOT NULL,
  discount_value numeric(10,2) NOT NULL,
  min_order_amount numeric(10,2) DEFAULT 0,
  max_discount_amount numeric(10,2),
  start_date timestamp with time zone NOT NULL,
  expiry_date timestamp with time zone NOT NULL,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  description text,
  applies_to varchar(20) DEFAULT 'all'::character varying,
  eligible_items jsonb,
  eligible_categories jsonb,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Financial management indexes
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);
CREATE INDEX IF NOT EXISTS idx_invoices_order_id ON invoices(order_id);
